import React from 'react';
import styles from '../styles/SubTopic.module.css';

const Education = () => {
   return (
      <div>
         <h2 className={styles.h2}>Education</h2>
         <p>To obtain a career in technology, having a solid education is essential. Namely, being able to communicate well both in written and spoken form, and appriecation of mathmatics are fundimental for getting started. While having deep knowledge of quantum electrodynamics, history of turing machines, or a Ph.D in Mathmatics is certainly not a requirement, it certainly doesn't hurt to want to study computer science and earn a degree in it at your chosen college or university. In fact, such an investment, when matched with good soft skills and a willingness to learn and grow over time, can certainly yield a great return on your investment of the course of your working life. That said, possessing a computer science or information technology degree is certain no longer a requirement for starting your career in technology.</p>
         <p>The key to getting your career started in technology is to first identify the kind of work that you want to do, which will hopefully be the kind of work that you find great fascination and passion in. Then you will want to search for job listings that fit the kind of work you want to do by linking certain keywords job-related tasks to job titles. These jobs will often share information about day to day responsiblities, duties, skills, and knowledge of certain tools or coding langauges that are necessary for the job. And from there, you can take those skills and tools and begin create a plan around learning them on your own or by taking classes.</p>
         <p>Citing myself for an example: I did not graduate from college with a computers science or IT degree. I was a liberal arts major. Years into working, I decided that I wanted to change careers and go from working in higher education to working with computers and making cool things for the world wide web. I found myself working for a history department professor doing content management for the deparments own website, a Wordpress Blog. Realizing that I was already learning certain skills about HTML, CSS and the command line, I took a course to learn more about writing programs for applications in languages like JavaScript and Ruby. From there, I worked on building a few small projects with what I had learned with the goal of demonstraiting a solid grap of how to build applciations with technologies like JavaScript. I build a small website for myself with each of these projects to showcase. I then spent months rewriting my resume and applying to jobs before landing my first job a junior software developer.</p>
         <p>The moral of this story is that working in tech is possible if you are someone who loves to learn new things, lovess to analyze and solve important problems, has great empathy for working well with other individuals, and perhaps has an amazing sense of humor as well (this last one is optional).</p>
      </div>
   )
}

export default Education;